table Crude_Prices
	lineageTag: bed7c6dd-b115-4652-8473-7c7f575bab8e

	column YEAR
		dataType: double
		lineageTag: 67d50dc7-999b-4a43-87b4-30b0b36caab0
		summarizeBy: none
		sourceColumn: YEAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MONTH
		dataType: double
		lineageTag: 190f845a-3315-48ac-bf2f-d96a34b22a1c
		summarizeBy: sum
		sourceColumn: MONTH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE
		dataType: string
		lineageTag: 8666ac6b-10c1-4626-970b-0be5cc506f35
		summarizeBy: none
		sourceColumn: SOURCE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UNIT
		dataType: string
		lineageTag: 3e8f64e6-54b7-463a-a596-fd4bbbc3a376
		summarizeBy: none
		sourceColumn: UNIT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COST
		dataType: double
		lineageTag: abb41710-eb69-4c4c-8c42-3bafdfcd0e42
		summarizeBy: sum
		sourceColumn: COST

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearMonth
		dataType: string
		lineageTag: d75dc406-6552-48fb-972c-6c1607b030b4
		summarizeBy: none
		sourceColumn: YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YearQuarter
		dataType: string
		lineageTag: d7798b7e-7509-4fdb-8378-2fa21d391640
		summarizeBy: none
		sourceColumn: YearQuarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QUARTER
		dataType: string
		lineageTag: d5b73931-1fca-479e-953c-f209209b4124
		summarizeBy: none
		sourceColumn: QUARTER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Crude_Prices = m
		mode: import
		queryGroup: 'Queries to Upload'
		source = ```
				let
				    Fonte = Excel.Workbook(File.Contents(Crude_Oil_Prices_Excel_Path)),
				    FiltrarFolhasOcultas = Table.SelectRows(Fonte, each ([Kind] = "Sheet") and ([Hidden] = false)),
				    AbrirFolha = FiltrarFolhasOcultas { [Item = "FUEL | CRUDE OIL SPOT", Kind = "Sheet"]}[Data],
				    PromoverCabeçalhos = Table.PromoteHeaders(AbrirFolha, [PromoteAllScallar=true]),
				    RemoverColuna = Table.RemoveColumns(PromoverCabeçalhos, {"PROVIDER"}),
				    AlterarTitulo = Table.RenameColumns(RemoverColuna, {"COS", "COST"}),
				    AlterarTipo = Table.TransformColumnTypes(AlterarTitulo, {{"YEAR", type number}, {"MONTH", type number}, {"SOURCE", type text}, {"UNIT", type text}, {"COST", type number}}),
				    ArrendondarCusto = Table.TransformColumns(AlterarTipo, {{"COST", each Number.Round(_, 2), type number}}), //O tipo de dado tem de ser expresso, caso contrário volta a any quando se usa a função transformcolumns
				    SelecionarLinhas = Table.SelectRows(ArrendondarCusto, each [YEAR] >= StartYear),
				    AdicionarQuarter = Table.AddColumn(SelecionarLinhas, "QUARTER", each if [MONTH] <= 3 then "Q1" else if [MONTH] <= 6 then "Q2" else if [MONTH] >= 9 then "Q3" else "Q4", type text),
				    AdicionarYearQuarter = Table.AddColumn(AdicionarQuarter, "YearQuarter", each Text.From([YEAR]) & [QUARTER], type text),
				    AdicionarYearMonth = Table.AddColumn(AdicionarYearQuarter, "YearMonth", each Text.From([YEAR]) & Text.From([MONTH]), type text),
				    ReordenarColunas = Table.ReorderColumns(AdicionarYearMonth, {"YEAR", "MONTH", "YearMonth", "YearQuarter", "SOURCE", "UNIT", "COST"})
				    
				in
				ReordenarColunas
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

