table Dim_Species
	lineageTag: 19656651-b41e-47c6-8fee-a4dbc9d35224

	column Index
		dataType: int64
		formatString: 0
		lineageTag: c3c55b20-d1e5-42cb-a674-9733a3956fd1
		summarizeBy: sum
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Species Code'
		dataType: string
		lineageTag: 9205917a-9554-4719-8d5a-f43c5de5af23
		summarizeBy: none
		sourceColumn: Species Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Species Name'
		dataType: string
		lineageTag: 71283fea-50cd-4ac8-8b98-328ae845b746
		summarizeBy: none
		sourceColumn: Species Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Species Category Code'
		dataType: string
		lineageTag: 0afe87fc-7383-443d-9a75-cb33abbc7b40
		summarizeBy: none
		sourceColumn: Species Category Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Species Category'
		dataType: string
		lineageTag: 4ba25047-7d84-47d5-af39-1b37f49d549b
		summarizeBy: none
		sourceColumn: Species Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_Species = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    ColunasPretendidas = {"Species Category Code", "Species Category", "Species Code", "Species Name"},
				    VerificarColunas = List.Select(ColunasPretendidas, each List.Contains(Table.ColumnNames(Catch_Estimates),_)),
				    SelecionarColunas = Table.SelectColumns(Catch_Estimates, VerificarColunas),
				    ColunasPretendidasEffort= {"SPECIES_CATEGORY_CODE", "SPECIES_CATEGORY", "SPECIES_CODE", "SPECIES"},
				    VerificarColunasEffort= List.Select(ColunasPretendidasEffort, each List.Contains(Table.ColumnNames(Fishing_Effort),_)),
				    SelecionarColunasEffort = Table.SelectColumns(Fishing_Effort, VerificarColunasEffort),
				    UniformizarColunas = Table.RenameColumns(SelecionarColunasEffort, {{"SPECIES_CATEGORY_CODE","Species Category Code"}, {"SPECIES_CATEGORY", "Species Category"}, {"SPECIES_CODE", "Species Code"}, {"SPECIES", "Species Name"}}),
				    CombinarTabelas = Table.Combine({SelecionarColunas, UniformizarColunas}),
				    SelecionarDistintos = Table.Distinct(CombinarTabelas, {"Species Code"}),
				    Index= Table.AddIndexColumn(SelecionarDistintos, "Index", 1, 1, Int64.Type),
				    ReordenarColunas = Table.ReorderColumns(Index, {"Index", "Species Code", "Species Name", "Species Category Code", "Species Category"}) 
				in
				    ReordenarColunas
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

