table Tuna_Import_Prices
	lineageTag: 19ea7208-7f27-459f-a8b6-d610b0467b60

	column 'Market Description'
		dataType: string
		lineageTag: f9fa7bcf-e18c-4c4d-ab97-f34e2f321aaf
		summarizeBy: none
		sourceColumn: Market Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fish Condition'
		dataType: string
		lineageTag: dc7deabb-9715-4320-96cf-797ec72cd423
		summarizeBy: none
		sourceColumn: Fish Condition

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gear
		dataType: string
		lineageTag: 5ee82d93-6f39-41ff-b77a-e4f07b02f2dd
		summarizeBy: none
		sourceColumn: Gear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Species Code'
		dataType: string
		lineageTag: db0bd30f-ed4e-4642-b4e7-3b4bebdf8cf4
		summarizeBy: none
		sourceColumn: Species Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Price per kg'
		dataType: double
		formatString: 0.00
		lineageTag: 8bf68c11-8a98-44c8-975c-b1a443258825
		summarizeBy: sum
		sourceColumn: Price per kg

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: double
		lineageTag: c3e2878f-b065-4e8b-b595-0e3dda813d8a
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Month
		dataType: double
		lineageTag: 756506b3-0fb1-4bdf-8618-f08d99aa57a5
		summarizeBy: sum
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YearMonth
		dataType: double
		lineageTag: 24965c76-46c2-4414-814f-a0305f0b4de3
		summarizeBy: none
		sourceColumn: YearMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unit
		dataType: string
		lineageTag: 93a6486e-c168-4b03-ae76-cf152166d4c0
		summarizeBy: none
		sourceColumn: Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Tuna_Import_Prices = m
		mode: import
		queryGroup: 'Queries to Upload'
		source = ```
				let
				   
				    Fonte = Excel.Workbook(File.Contents(#"Fish_Prices_Excel_Path")),
				    FiltrarFolhasOcultas = Table.SelectRows(Fonte, each ([Kind] = "Sheet") and ([Hidden] = false)),
				    PromoverCabeçalhos = Table.TransformColumns(FiltrarFolhasOcultas, {{"Data", Table.PromoteHeaders}}),
				    CombinarFolhas = Table.Combine(PromoverCabeçalhos[Data]),
				    RemoverProvider = Table.RemoveColumns(CombinarFolhas, "PROVIDER"),
				    AlterarTipos = Table.TransformColumnTypes(RemoverProvider, {{"YEAR", type number}, {"MONTH", type number}, {"SOURCE", type text}, {"UNIT", type text},{"SKJ", type number}, {"YFT", type number}, {"BET", type number}, {"ALB", type number}}),
				    RenomearColunas = Table.RenameColumns(AlterarTipos, {{"YEAR", "Year"},{"MONTH", "Month"}, {"SOURCE", "Source"}, {"UNIT", "Unit"}}),
				    AlterarNulls = Table.ReplaceValue(RenomearColunas, null, 0.0, Replacer.ReplaceValue, {"SKJ","YFT", "BET", "ALB"}),
				    ArredondarValores = Table.TransformColumns(AlterarNulls, {{"SKJ", each Number.Round(_,2), type number},{"YFT", each Number.Round(_,2), type number}, {"BET",  each Number.Round(_,2), type number}, {"ALB",  each Number.Round(_,2), type number}}),
				    //TransformColumns faz o reset ao data type das colunas para type any sempre que é realizada uma transformação iterante (each). Expressar sempre o data type como 3º elemento de cada transformação.
				    AdicionarColunasCategoricas = let 
				        AdicionarTipoPescaria = Table.AddColumn(ArredondarValores, "Fisheries" , each Text.Split(Text.Trim([Source]), "|"){0}, type text),
				        AdicionarDescricaoMercado = Table.AddColumn(AdicionarTipoPescaria, "Market Description", each Text.Split(Text.Trim([Source]), "|"){1}, type text),
				        AdicionarEstadoPescado = Table.AddColumn(AdicionarDescricaoMercado, "Fish Condition", each Text.Split(Text.Trim([Fisheries]), " "){0}, type text ),
				        AdicionarAparelhoCaptura =  Table.AddColumn(AdicionarEstadoPescado, "Gear", each Text.AfterDelimiter(Text.Trim([Fisheries])," ", 0), type text ),
				        AdicionarMaiusculas = Table.TransformColumns(AdicionarAparelhoCaptura, {{"Gear", each Text.Proper(_), type text}}),
				        RemoverColunas = Table.RemoveColumns(AdicionarMaiusculas, {"Source", "Fisheries"}),
				        ReordenarColunas = Table.ReorderColumns(RemoverColunas, {"Year", "Month", "Market Description" ,"Fish Condition", "Gear", "Unit", "SKJ", "YFT", "BET", "ALB"})
				    in 
				    ReordenarColunas,
				
				    UniformizarPreços_TonsParaKgs = List.Accumulate({"SKJ", "YFT", "BET", "ALB"}, AdicionarColunasCategoricas,  (state,current) => Table.ReplaceValue ( state, each Record.Field(_,current), each if [Unit] = "USD per tonne" and Record.Field(_,current) <> 0.0 then Record.Field(_,current) / 1000 
				        else Record.Field(_,current), Replacer.ReplaceValue, {current})),
				  // List.Acumulate permite processar linha a linha mantendo um estado anterior, não alterando valores fora do If. É a única forma de usar ReplaceValue de forma correcta, linha a linha, comparando condições em múltiplas colunas.
				    UniformizarUnit = Table.ReplaceValue(UniformizarPreços_TonsParaKgs, "USD per tonne", "USD per kg", Replacer.ReplaceValue, {"Unit"}), 
				 // Valores de conversão da Federal Reserve August 2026
				    ConvertYen =  List.Accumulate({"SKJ", "YFT", "BET", "ALB"}, UniformizarUnit, (state,current) => Table.ReplaceValue ( state, each Record.Field(_,current), each if [Unit] = "YEN per kg" and Record.Field(_,current) <> 0.0 then Record.Field(_,current) * 0.0063
				        else Record.Field(_,current), Replacer.ReplaceValue, {current})),
				    UniformizarUnitYENtoUSD = Table.ReplaceValue(ConvertYen, "YEN per kg", "USD per kg", Replacer.ReplaceValue, {"Unit"}),
				    SelecionarLinhas = Table.SelectRows(UniformizarUnitYENtoUSD, each [Year]>=StartYear),
				    UnpivotColunas = Table.UnpivotOtherColumns(SelecionarLinhas,{"Year", "Month", "Market Description","Fish Condition", "Gear", "Unit"}, "Species Code", "Price per kg"),
				    DefinirTipoValCol = Table.TransformColumnTypes(UnpivotColunas, {{"Price per kg", type number}}),
				    AdicionarYearMonth = Table.AddColumn(DefinirTipoValCol, "YearMonth", each [Year]*100 + [Month], type number),
				    ReordenarColunas = Table.ReorderColumns(AdicionarYearMonth, {"Year", "Month","YearMonth" ,"Market Description" ,"Fish Condition", "Gear", "Unit", "Species Code", "Price per kg"})
				
				in
				    ReordenarColunas
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

