table Dim_Fate
	lineageTag: 3bee588c-118b-40e4-a836-836193311d01

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 2d5e4e7a-58af-457a-ac39-64e5013053b8
		summarizeBy: sum
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fate
		dataType: string
		lineageTag: d5986455-11f5-45e1-8d68-e4389e1d0b63
		summarizeBy: none
		sourceColumn: Fate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fate Code'
		dataType: string
		lineageTag: 110ee370-b187-435d-b63d-4098358a3071
		summarizeBy: none
		sourceColumn: Fate Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_Fate = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    ColunasPretendidas = {"Fate Code", "Fate"},
				    VerificarColunas = List.Select(ColunasPretendidas, each List.Contains(Table.ColumnNames(Catch_Estimates),_)),
				    SelecionarColunas = Table.SelectColumns(Catch_Estimates, VerificarColunas),
				    AplicarDistinct = Table.Distinct(SelecionarColunas, {"Fate Code"}),
				    Index = Table.AddIndexColumn(AplicarDistinct, "Index", 1, 1, Int64.Type),
				    ReordenarColunas =  Table.ReorderColumns(Index, {"Index", "Fate", "Fate Code"})
				
				
				in
				    ReordenarColunas

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

