table IOTC_Major_Geo_Areas
	lineageTag: 79e8910a-ff2e-4835-bc36-4b61c6160a0e

	column code
		dataType: string
		lineageTag: a0efe638-4b28-4c63-9bf7-ce01e1216c4f
		summarizeBy: none
		sourceColumn: code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column name_en
		dataType: string
		lineageTag: 4204bf00-6662-466c-bd35-b9780cff2c84
		summarizeBy: none
		sourceColumn: name_en

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ocean_area_km2
		dataType: double
		lineageTag: c7f66356-4688-4f80-abf9-c1c8f6aed8c9
		summarizeBy: none
		sourceColumn: ocean_area_km2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ocean_area_iotc_km2
		dataType: double
		lineageTag: a6416b18-fe3e-4cb0-9287-3a29a7ae8528
		summarizeBy: none
		sourceColumn: ocean_area_iotc_km2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column center_lat
		dataType: double
		lineageTag: 5661b58f-ada5-4afc-a69f-8c3b03606cc4
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: center_lat

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column center_lon
		dataType: double
		lineageTag: 4ff27b76-d2b1-4065-8ee9-962c5b6f0280
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: center_lon

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition IOTC_Major_Geo_Areas = m
		mode: import
		queryGroup: 'Queries to Upload'
		source =
				let
				    Fonte = Csv.Document(File.Contents(Geographical_Data_Connection)),
				    PromoverCabeçalhos = Table.PromoteHeaders(Fonte, [PromoteAllScalars = true]),
				    SelecionarColunas = Table.SelectColumns(PromoverCabeçalhos, {"code", "name_en", "ocean_area_km2",	"ocean_area_iotc_km2",	"center_lat",	"center_lon"}),
				    AlterarDataTypes = Table.TransformColumnTypes(SelecionarColunas, {{"code", type text}, {"name_en", type text}, {"ocean_area_km2", type number}, {"ocean_area_iotc_km2", type number}, {"center_lat", type number}, {"center_lon", type number}}),
				    TrimCode = Table.TransformColumns(AlterarDataTypes, {{"code", each Text.Trim(_), type text}}), //Table.TransformColumns já itera automaticamente. Não esquecer de colocar dentro de uma lista {{}} ({} interno é para a sublista que é cada linha). each Text.Trim(_) poderia ser so Text.Trim, mas assim é mais fácil de perceber a mecanica. Sempre usar o opcional datatype, caso contratio a coluna fica como any type.
				    UniformizarCodigosList = {{"IO_WEST", "IRWESIO"}, {"IO_EAST", "IREASIO"}, {"", "Not specified"}},
				    UniformizarCódigosReplace=  List.Accumulate(UniformizarCodigosList, TrimCode, (state, current) => Table.ReplaceValue(state, current{0},current{1}, Replacer.ReplaceValue, {"code"}))
				in
				    UniformizarCódigosReplace

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

